Update private-build-compiled-mastodon.yml

diff --git a/.github/workflows/private-build-compiled-mastodon.yml b/.github/workflows/private-build-compiled-mastodon.yml
--- a/.github/workflows/private-build-compiled-mastodon.yml
+++ b/.github/workflows/private-build-compiled-mastodon.yml
@@ -25,6 +25,10 @@ jobs:
         platform:
           - linux/amd64
     steps:
+      - name: Check secrets availability
+        run: |
+          if [ -z "${{ secrets.DOCKER_HUB_USER_NAME }}" ]; then echo "DOCKER_HUB_USER_NAME is missing"; exit 1; fi
+          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then echo "DOCKER_HUB_ACCESS_TOKEN is missing"; exit 1; fi
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
