Update private-build-compiled-mastodon.yml

diff --git a/.github/workflows/private-build-compiled-mastodon.yml b/.github/workflows/private-build-compiled-mastodon.yml
--- a/.github/workflows/private-build-compiled-mastodon.yml
+++ b/.github/workflows/private-build-compiled-mastodon.yml
@@ -1,4 +1,4 @@
-name: Build Compiled Mastodon Container
+name: Build Compiled Mastodon Container - v1
 run-name: ${{ github.actor }}
 
 on:
@@ -18,12 +18,17 @@ on:
 jobs:
   Mastodon-Mastoapp-1-Build-Container:
     runs-on: ubuntu-22.04
+    environment: containerbuild
     strategy:
       fail-fast: false
       matrix:
         platform:
           - linux/amd64
     steps:
+      - name: Check secrets availability
+        run: |
+          if [ -z "${{ secrets.DOCKER_HUB_USER_NAME }}" ]; then echo "DOCKER_HUB_USER_NAME is missing"; exit 1; fi
+          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then echo "DOCKER_HUB_ACCESS_TOKEN is missing"; exit 1; fi
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -66,5 +71,5 @@ jobs:
             "ARG_VAPID_PUBLIC_KEY=${{ secrets.ARG_VAPID_PUBLIC_KEY }}"
             "DOCKER_HUB_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
             "DOCKER_HUB_USER_NAME=${{ secrets.DOCKER_HUB_USER_NAME }}"
-          context: "{{defaultContext}}:."
+          context: "{{defaultContext}}"
           file: Dockerfile
